version: '3'
services: 
    api-service:
        build: ./api-sn/
        volumes: 
            - ./api-sn/:/usr/src/app/
        ports: 
            - 5000:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1
