version: '3'
services:
    jupyter:
        build: ./jupyter/
        volumes: 
            - ./jupyter/:/usr/src/app/
        ports: 
            - 8888:8888      
    api-service:
        build: ./api-sn/
        volumes: 
            - ./api-sn/:/usr/src/app/
        ports: 
            - 5000:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1
            MYSQL_DATABASE: social_net
            MYSQL_ROOT_PASSWORD : root
    db:
        image: mysql:8.0.19
        command: '--default-authentication-plugin=mysql_native_password'
        volumes:
            - db-data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=social_net
            - MYSQL_ROOT_PASSWORD=root
    nginx:
        build: ./nginx/
        ports:
          - 80:80
volumes:
  db-data:
