version: '3'
services: 
    api-service:
        build: ./api-sn/
        volumes: 
            - ./api-sn/:/usr/src/app/
        ports: 
            - 80:80
        environment: 
            PORT: 80
            FLASK_DEBUG: 1
